### ISSUE TITLE
go1.18-openssl-fips: building toolchain2 fails with undefined reference to `dlsym'

### ISSUE THREAD

**Issue by ueno** [golang-fips/go#3]
I tried to build the new `go1.18-openssl-fips` branch on Fedora, with:
```console
GOROOT_BOOTSTRAP=/ GOROOT_FINAL=/usr/lib/golang GOHOSTOS=linux GOHOSTARCH=amd64 GOOS=linux GOARCH=amd64 ./make.bash -v
```
but got this error:
```console
Building Go toolchain2 using go_bootstrap and Go toolchain1.
...
# crypto/internal/boring
/usr/bin/ld: $WORK/b061/_x002.o: in function `_goboringcrypto_EVP_CIPHER_CTX_free':
/_/crypto/internal/boring/goopenssl.h:668: undefined reference to `dlsym'
/usr/bin/ld: $WORK/b061/_x002.o: in function `_goboringcrypto_EVP_CIPHER_CTX_new':
/_/crypto/internal/boring/goopenssl.h:287: undefined reference to `dlsym'
...
```
@derekparker any ideas? The same command succeeds with the `go1.17-openssl-fips` branch (3ece7d349521057450d587a94a495b2c476d0d88).

**Comment by derekparker** [comment]
Are you using OpenSSL 3.0? In that case @dbenoit17 if finishing up adding OpenSSL 3.0 support right now.

**Comment by dbenoit17** [comment]
@ueno I can not reproduce this, but it looks like go1.17-openssl-fips provides -ldl in #cgo LDFLAGS, which we may want to add to the 1.18 branch.  Could you test if this patch resolves your issue?

https://github.com/golang-fips/go/commit/f31bc5d8a4e6a365213761e4730daa7818e2f016

**Comment by ueno** [comment]
@dbenoit17 thanks; after changing `#cgo LDFLAGS: "-pthread -ldl"` to `#cgo LDFLAGS: "-pthread" "-ldl"` (note the quotation), it works.

**Comment by derekparker** [comment]
Sorry, I overlooked that `dlsym` was the missing symbol, my brain read it as if the EVP_* symbols were missing hence my question on OpenSSL 3.

That `LDFLAGS` section was changed during the rebase because upstream added `-lpthread` however we don't need it in our fork. I'm testing a patch to fix this now. Odd it didn't come up sooner.
