### ISSUE TITLE
crypto/boring: build constraints exclude all Go files

### ISSUE THREAD

**Issue by dbenoit17** [golang-fips/go#59]
The following program:

```
package main
import (
    "fmt"
    "crypto/boring"
)

func main() {
    fmt.Println("boring enabled:", boring.Enabled())
}
```

Produces the error
```
imports crypto/boring: build constraints exclude all Go files in /usr/lib/golang/src/crypto/boring
```

This is due to the public API missing the build tag change to `!no_openssl`.  However, the curious thing is that running with `-tags="boringcrypto"` does not resolve the issue.  @derekparker any thoughts?

**Comment by derekparker** [comment]
We can work around this by prefixing `GOEXPERIMENT=boringcrypto` to the `go build` command.
